#!/usr/bin/env sh
# Generate the API reference page from `go doc`, embedded under the docs
# site's Reference section. Runs inside the build (Go) container as the
# first step of `task build:docs` — NOT on the host, NOT in the docs
# container. Overwrites docs/content/reference/api.md.
set -eu

OUT=docs/content/reference/api.md

{
	echo "# API reference"
	echo
	echo "Generated by \`go doc\` as part of \`task build:docs\`. Do not edit by hand —"
	echo "changes here are overwritten on the next docs build."
	echo
	for pkg in . ./cmd; do
		echo "## Package \`${pkg}\`"
		echo
		echo '```text'
		go doc -all -u "${pkg}" 2>/dev/null || echo "(no symbols)"
		echo '```'
		echo
	done
} >"${OUT}"

echo "Wrote ${OUT}"
